{% set version = "1.11.0" %}

package:
  name: libfido2
  version: {{ version }}

source:
  url: https://github.com/Yubico/libfido2/archive/{{ version }}.tar.gz
  sha256: 0830c5853e3b44099a97166e0cec54a65b54b7faaac07071872f77b8e4d7b302

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libfido2', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - openssl
    - libcbor
    - libudev  # [linux]
    - zlib

test:
  commands:
    - test -f "${PREFIX}/lib/libfido2${SHLIB_EXT}"

about:
  home: https://github.com/Yubico/libfido2/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Provides library functionality for FIDO 2.0

extra:
  recipe-maintainers:
    - chrisburr
